### PR TITLE
Added deep equality checks for undoing actions

### PR DESCRIPTION
**Pull request by krzysztofsaja**

### CODE REVIEW

**Comment by brechtbilliet** [comment]
I'm afraid I can't merge this once since this will hurt the performance of the application. The reason why the current version is performant is because they check references, and every action has its own reference. Is there a reason why the current version doesn't work for you?

**Review by SamVerschueren — COMMENTED** [review]
Why? I believe this will cause unwanted side effects. If I create 2 items with the exact same payload, but I only want to undo the second create, both actions will be rejected. Checking if the references are the same is exactly what we want, no?

**Comment by krzysztofsaja** [comment]
Hi, I don't know your implementations but the original version just doesn't work for me. I believe that you tested undo functionality with assumption that redux action is a plain object cached in one variable. But in my application I've got action creators functions (common redux pattern) that return new action object every time. Because of this filtering actions in `handleUndo.ts` solely by reference just doesn't work. Maybe where should be some initialization options to choose from shallow or deep equality comparisons.

**Comment by SamVerschueren** [comment]
The thing is that you have to undo the original action, not a new one, that's the whole idea. Like I said in my previous comment, if you create 2 todo items with the exact same content

```js
{
    type: 'ADD_TODO',
    payload: {
        title: 'My todo'
    }
}
```

```js
const todo1 = MyActionCreator.addTodo('My Todo');

dispatch(todo1);

const todo2 = MyActionCreator.addTodo('My Todo');

dispatch(todo2);

// Undo the second one
dispatch(undo(todo2));
```

With this PR I will end up with 0 todos because it checks the content. Not what you would expect. When you undo an action, you will have to call `undo` with the original action (see my example), not with a new one.

**THIS IS WRONG!**

```js
const todo = MyActionCreator.addTodo('My Todo');

dispatch(todo);

// Undo
dispatch(undo(MyActionCreator.addTodo('My Todo')));
```

**THIS IS CORRECT!**

Because we use the same reference, which is very important!

```js
const todo = MyActionCreator.addTodo('My Todo');

dispatch(todo);

// Undo
dispatch(undo(todo));
```

**Comment by brechtbilliet** [comment]
very well explained! You indeed want to keep a reference to your action. Otherwise it will never work :)

**Comment by krzysztofsaja** [comment]
OK. Thanks for you answers. I refactor my code to pass original action object to undo and it works well. I didn't think that it works based on reference because redux architecture is based on coping objects and immutability so I don't rely on references much.

**Pull request closed without merging**
