### PR TITLE
add node 7

### PR DESCRIPTION
**Pull request by vdclouis**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Never noticed it was restricted like that. I would actually change that line to `>=4.x`. I don't see any valid reason why the boundries should be set this restrictive.

**Comment by vdclouis** [comment]
I'll update it

**Comment by SamVerschueren** [comment]
Well, it's @brechtbilliet his module so it's not my call to make. Just giving my opinion.

**Comment by brechtbilliet** [comment]
Thanks for your PR :)

**Pull request merged**
